apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:yourorg/infra.git
    targetRevision: main
    path: charts/user
    helm:
      valueFiles:
        - apps/dev/user-service/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
